import { NextResponse } from 'next/server';
import { getServiceRoleSupabaseClient } from '@/lib/supabase';
import { auth } from "@/auth.js";

// Initialize Supabase client with service role key for admin operations
const supabase = getServiceRoleSupabaseClient();

/**
 * GET /api/participants - Retrieve all participants
 * Returns a list of all participants ordered by creation date (newest first)
 */
export async function GET() {
  try {
    const { data, error } = await supabase
      .from('participants')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json(
        { success: false, error: 'Failed to fetch participants' },
        { status: 500 }
      );
    }

    // Transform database records to match frontend Participant interface
    const transformedData = (data || []).map((participant: any) => {
      if (!participant.created_at) {
        throw new Error(`Missing created_at for participant with id: ${participant.id}. Please correct the database.`);
      }
      return {
        id: participant.id,
        name: participant.name,
        email: participant.email,
        phone: participant.phone,
        event: participant.event,
        registrationTime: participant.created_at,
        status: participant.status || 'registered',
        qrCode: participant.id, // Use participant ID as QR code identifier
      };
    });

    return NextResponse.json({ success: true, data: transformedData });
  } catch (error) {
    console.error('API error:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch participants' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/participants - Create a new participant
 * Requires authentication and phone number in request body
 * Validates input and prevents duplicate registrations
 */
export async function POST(req: Request) {
  const session = await auth();
  const user = session?.user;

  if (!user) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const { phone, event = 'Janmashtami 2025' } = await req.json();
    const { name, email } = user;

    // Validate required fields from user session and request
    if (!name || !email) {
      return new Response("Missing required fields: name or email", { status: 400 });
    }

    if (!phone) {
      return new Response("Missing required field: phone", { status: 400 });
    }

    // Validate phone number format (10 digits)
    if (!/^\d{10}$/.test(phone)) {
      return new Response("Phone number must be 10 digits", { status: 400 });
    }

    // Check for existing participant to prevent duplicates
    const { data: existingParticipant } = await supabase
      .from('participants')
      .select('id')
      .eq('email', email)
      .eq('event', event)
      .single();

    if (existingParticipant) {
      return new Response("Participant with this email already exists for this event", { status: 409 });
    }

    // Insert new participant record with required event field
    const { data, error } = await supabase
      .from('participants')
      .insert([
        {
          name,
          email,
          phone,
          event,
          status: 'registered',
          // created_at will be auto-generated by Supabase
        },
      ])
      .select();

    if (error) {
      console.error('Supabase insert error:', error);
      return new Response(`Database error: ${error.message}`, { status: 500 });
    }

    // Transform created participant to match frontend interface
    const transformedParticipant = {
      id: data[0].id,
      name: data[0].name,
      email: data[0].email,
      phone: data[0].phone,
      event: data[0].event,
      registrationTime: data[0].created_at || new Date().toISOString(),
      status: data[0].status || 'registered',
      qrCode: data[0].id,
    };

    return new Response(JSON.stringify({ success: true, data: transformedParticipant }), { status: 201 });
  } catch (error) {
    console.error('API error:', error);
    return new Response("Internal server error", { status: 500 });
  }
}