import { NextResponse } from 'next/server';
import { getServiceRoleSupabaseClient } from '@/lib/supabase';
import { auth } from "@/auth.js";
import { API_MESSAGES, HTTP_STATUS, EVENT_CONSTANTS, DB_TABLES } from '@/lib/constants';
import { validatePhoneNumber, validateName, validateEmail } from '@/lib/validation';

// Initialize Supabase client with service role key for admin operations
const supabase = getServiceRoleSupabaseClient();

/**
 * GET /api/participants - Retrieve all participants
 * Returns a list of all participants ordered by creation date (newest first)
 */
export async function GET() {
  try {
    const { data, error } = await supabase
      .from(DB_TABLES.PARTICIPANTS)
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json(
        { error: 'Failed to fetch participants' },
        { status: HTTP_STATUS.INTERNAL_SERVER_ERROR }
      );
    }

    // Transform database records to match frontend Participant interface
    const transformedData = (data || []).map((participant: any) => {
      if (!participant.created_at) {
        throw new Error(`Missing created_at for participant with id: ${participant.id}. Please correct the database.`);
      }
      return {
        id: participant.id,
        name: participant.name,
        email: participant.email,
        phone: participant.phone,
        event: participant.event,
        registrationTime: participant.created_at,
        status: participant.status || EVENT_CONSTANTS.STATUS.REGISTERED,
        qrCode: participant.id, // Use participant ID as QR code identifier
      };
    });

    return NextResponse.json({ data: transformedData });
  } catch (error) {
    console.error('API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch participants' },
      { status: HTTP_STATUS.INTERNAL_SERVER_ERROR }
    );
  }
}

/**
 * POST /api/participants - Create a new participant
 * Requires authentication and phone number in request body
 * Validates input and prevents duplicate registrations
 */
export async function POST(req: Request) {
  const session = await auth();
  const user = session?.user;

  if (!user) {
    return new Response(API_MESSAGES.UNAUTHORIZED, { status: HTTP_STATUS.UNAUTHORIZED });
  }

  try {
    const { phone, event = EVENT_CONSTANTS.DEFAULT_EVENT } = await req.json();
    const { name, email } = user;

    // Validate required fields from user session and request
    if (!name || !email) {
      return new Response("Missing required fields: name or email", { status: HTTP_STATUS.BAD_REQUEST });
    }

    const nameValidation = validateName(name);
    if (!nameValidation.isValid) {
      return new Response(nameValidation.error, { status: HTTP_STATUS.BAD_REQUEST });
    }

    const emailValidation = validateEmail(email);
    if (!emailValidation.isValid) {
      return new Response(emailValidation.error, { status: HTTP_STATUS.BAD_REQUEST });
    }

    const phoneValidation = validatePhoneNumber(phone);
    if (!phoneValidation.isValid) {
      return new Response(phoneValidation.error, { status: HTTP_STATUS.BAD_REQUEST });
    }

    // Check for existing participant to prevent duplicates
    const { data: existingParticipant } = await supabase
      .from(DB_TABLES.PARTICIPANTS)
      .select('id')
      .eq('email', email)
      .eq('event', event)
      .single();

    if (existingParticipant) {
      return new Response("Participant with this email already exists for this event", { status: HTTP_STATUS.CONFLICT });
    }

    // Insert new participant record with required event field
    const { data, error } = await supabase
      .from(DB_TABLES.PARTICIPANTS)
      .insert([
        {
          name,
          email,
          phone,
          event,
          status: EVENT_CONSTANTS.STATUS.REGISTERED,
          // created_at will be auto-generated by Supabase
        },
      ])
      .select();

    if (error) {
      console.error('Supabase insert error:', error);
      return new Response(`Database error: ${error.message}`, { status: HTTP_STATUS.INTERNAL_SERVER_ERROR });
    }

    // Transform created participant to match frontend interface
    const transformedParticipant = {
      id: data[0].id,
      name: data[0].name,
      email: data[0].email,
      phone: data[0].phone,
      event: data[0].event,
      registrationTime: data[0].created_at || new Date().toISOString(),
      status: data[0].status || EVENT_CONSTANTS.STATUS.REGISTERED,
      qrCode: data[0].id,
    };

    return new Response(JSON.stringify({ data: transformedParticipant }), { status: HTTP_STATUS.CREATED });
  } catch (error) {
    console.error('API error:', error);
    return new Response(API_MESSAGES.INTERNAL_SERVER_ERROR, { status: HTTP_STATUS.INTERNAL_SERVER_ERROR });
  }
}